version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:gpu-nvidia-latest
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "6333:6333"
      - "6334:6334"
    environment:
      - QDRANT__GPU__INDEXING=1
      - QDRANT__SERVICE__API_KEY=YOUR_KEY
