global:
  scrape_interval: 10s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
        - prometheus:9090
  
  - job_name: node
    static_configs:
      - targets:
        - node-exporter:9100
  
  - job_name: qdrant
    authorization:
      credentials: "YOUR_KEY"
    static_configs:
      - targets:
        - ec2-52-23-219-145.compute-1.amazonaws.com:6333